language: cpp
compiler:
  - gcc
  - clang
cache: apt
before_install:
 - sudo add-apt-repository --yes ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake
before_script: mkdir build && cd build
script: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_ESCRIPT_APPLICATION=ON -DBUILD_ESCRIPT_TEST=ON .. && make && cd .. && build/tests/escript_test

